# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5fdbe0267c1dc263460ba4614f033ba58c4166637d5901719a56e96c86a2743b046031d04ba36d3f74797796a922b4743dc3ccb42a10866728a4fef4d4b5642

test:
  secret_key_base: 516a07f3e32d1b7952b8d34c00bd6905023f1caa8ebd3429d1b4c0e27bcd3ec7a2727401b2b082c9f6c78f4cb14eb5de834e5188f9a42ac65ab868903476581a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
